TasksEvaluation.Web/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TasksEvaluation.Web.ViewModels.RoleViewModels;

namespace TasksEvaluation.Web.Controllers
{

	[Authorize(Roles ="admin")]
	public class RoleController : Controller
	{
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;

                
        }
        public IActionResult AssignRoleToUser()
		{
			return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> AssignRoleToUser(AssignRoleToUserVM assignRoleToUserVM)
        {

            if(ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(assignRoleToUserVM.UserName);
                var isExistRole = await _roleManager.RoleExistsAsync(assignRoleToUserVM.RoleName);
                if (user is null || !isExistRole)
                    return NotFound();
                var assignResult = await _userManager.AddToRoleAsync(user, assignRoleToUserVM.RoleName);
                if (assignResult.Succeeded)
                    return RedirectToAction("GetAllStudents", "Student");

                
            }
            return View(assignRoleToUserVM);
        }


        public IActionResult RemoveRoleFromUser()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> RemoveRoleFromUser(AssignRoleToUserVM assignRoleToUserVM)
        {

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(assignRoleToUserVM.UserName);
                var isExistRole = await _roleManager.RoleExistsAsync(assignRoleToUserVM.RoleName);
                if (user is null || !isExistRole)
                    return NotFound();
                var assignResult = await _userManager.RemoveFromRoleAsync(user, assignRoleToUserVM.RoleName);
                if (assignResult.Succeeded)
                    return RedirectToAction("GetAllStudents", "Student");


            }
            return View(assignRoleToUserVM);
        }
    }
}

TasksEvaluation.Web/Controllers/SolutionController.cs
using Microsoft.AspNetCore.Mvc;
using TaskEvaluation.InfraStructure.Repositories.Services;
using TasksEvaluation.Core;
using TasksEvaluation.Core.DTOs;
using TasksEvaluation.Core.Entities.Business;
using TasksEvaluation.Core.Interfaces.IServices;
using TasksEvaluation.Web.ViewModels;

namespace TasksEvaluation.Web.Controllers
{
	public class SolutionController : Controller
	{

		private readonly ISolutionService _solutionService;
		private readonly IStudentService _studentService;
		private readonly IUnitOfWork _unitOfWork;

		public SolutionController(ISolutionService solutionService, IUnitOfWork unitOfWork , IStudentService studentService)
		{
			_solutionService = solutionService;
			_unitOfWork = unitOfWork;
			_studentService = studentService;


		}

		public async Task<IActionResult> GetAllSolutions()
		{
			var solutions = await  _solutionService.GetAll();
			return View(solutions);
		}

		public IActionResult Create(int studentId , int assignmentId) // , string studentEmail
		{
			ViewData["StudentId"] = studentId;
			ViewData["AssignmentId"] = assignmentId;
			//var loginAsStudentVM = new LoginAsStudentVM();
			//loginAsStudentVM.Email = studentEmail;
			//ViewData["LoginAsStudentVM"] = loginAsStudentVM;
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(SolutionCreateVM solutionVM)
		{
			if (ModelState.IsValid)
			{
				var solution = new SolutionDto()
				{
					AssignmentId = solutionVM.AssignmentId,
					StudentId = solutionVM.StudentId,
					Notes = solutionVM.Notes
				};
				if (solutionVM.SolutionFile != null)
				{
					string uploadsSolutionFilesFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads" ,"SolutionFiles");
					string fileName = Guid.NewGuid() + Path.GetExtension(solutionVM.SolutionFile.FileName);
					string filePath = Path.Combine(uploadsSolutionFilesFolder, fileName);


					using (var fileStream = new FileStream(filePath, FileMode.Create))
					{
						await solutionVM.SolutionFile.CopyToAsync(fileStream);
					}

					solution.SolutionFile = @$"/uploads/SolutionFiles/{fileName}";
				}
				await _solutionService.Create(solution);
				await _unitOfWork.Complete();
				var student = _studentService.GetById(solution.StudentId.Value).Result;
				return RedirectToAction(nameof(AssignmentController.GetAssignmentsAccordingSpecificStudent) ,"Assignment" , student);

			}
			return View(solutionVM);

		}

	}
}

TasksEvaluation.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
    @using Microsoft.AspNetCore.Identity;
    @inject SignInManager<IdentityUser> signInManager
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TasksEvaluation.Web.styles.css" asp-append-version="true" />
    <title> Admin Dashboard</title>
   
</head>
<style>
    body {
        display: flex;
        margin: 0;
        height: 100vh;
    }

    .sidenav {
        background-color: #f1f1f1;
        height: 100%;
        width: 150px;
        position: fixed;
        z-index: 1;
        overflow-x: hidden;
        padding-top: 20px;
    }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            display: block;
        }

            .sidenav a:hover {
                color: white;
                background-color: dodgerblue;
            }

    .main {
        margin-left: 300px;
        padding: 20px;
        height: 100%;
    }
</style>
<body>

        <div class="d-flex flex-column flex-shrink-0 p-3 bg-light sidenav" style="width: 280px;">
        <span class="fs-4 text-center">Dashboard</span>

            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                <a asp-controller="Student" asp-action="GetAllStudents" class="nav-link link-dark" aria-current="page">
                        <svg class="bi me-2" width="16" height="16"></svg>
                        Students
                    </a>
                </li>
                <li>
                <a asp-controller="Assignment" asp-action="GetAllAssignments" class="nav-link link-dark">
                        <svg class="bi me-2" width="16" height="16"><use xlink:href="#table" /></svg>
                        Assignments
                    </a>
                </li>
            <li>
                <a asp-controller="Solution" asp-action="GetAllSolutions" class="nav-link link-dark">
                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#table" /></svg>
                    Evaluate Solutions
                </a>
            </li>

            </ul>
            <hr>
            <div class="dropdown">
                <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
               <strong>@User?.Identity?.Name</strong>
                </a>
                <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdownUser2">
                @if (User.IsInRole("admin"))
                {
                    <li><a class="dropdown-item" asp-action="Register" asp-controller="Account">Create Instructor</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-action="DeleteUser" asp-controller="Account">Remove Instructor</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-action="AssignRoleToUser" asp-controller="Role">Promote Instructor</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" asp-action="RemoveRoleFromUser" asp-controller="Role">Demote Instructor</a></li>
                    <li><hr class="dropdown-divider"></li>
                }
               
                <li><a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">Change Password</a></li>
                    <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" asp-action="Logout" asp-controller="Account">Log out</a></li>
                </ul>
            </div>
        </div>

    <div class="container main bg-white">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TasksEvaluation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" name="viewport" />
	<title>@ViewData["Title"] - TasksEvaluation.Web</title>




	<meta content="" name="keywords">
	<meta content="" name="description">

	<!-- Favicon -->
	<link href="img/favicon.ico" rel="icon">

	<!-- Google Web Fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&display=swap" rel="stylesheet">

	<!-- Icon Font Stylesheet -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

	<!-- Libraries Stylesheet -->
	<link href="/lib/animate/animate.min.css" rel="stylesheet">
	<link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

	<!-- Customized Bootstrap Stylesheet -->
	<link href="/css/bootstrap.min.css" rel="stylesheet">

	<!-- Template Stylesheet -->
	<link href="/css/style.css" rel="stylesheet">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/TasksEvaluation.Web.styles.css" asp-append-version="true" />
	<style>
		.nav-item.nav-link:hover {
			color: #0d6efd !important; /* Change to your desired hover color */
		}
	</style>
</head>

<body>

	@*  <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
	<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TasksEvaluation.Web</a>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
	aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
	</button>
	<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	<ul class="navbar-nav flex-grow-1">
	<li class="nav-item">
	<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
	</li>
	<li class="nav-item">
	<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	</li>
	</ul>
	<partial name="_LoginPartial" />
	</div>
	</div>
	</nav> *@

	<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0 ">
		<a asp-controller="Home" asp-action="Index" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
			<h2 class="m-0 text-primary"><i class="fa fa-book me-3"></i>Tasks Evaluation</h2>
		</a>
		<button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<div class="navbar-nav ms-auto p-4 p-lg-0">
				<a asp-controller="Home" asp-action="Index" class="nav-item nav-link">Home</a>
				<a href="/#about" class="nav-item nav-link">About</a>
				<a href="/#Contact" class="nav-item nav-link">Contact</a>
				<a asp-controller="Account" asp-action="Login" class="nav-item nav-link">Login</a>
				<a asp-controller="Student" asp-action="LoginAsStudent" class="nav-item nav-link">Login As Student</a>
			</div>
		</div>
	</nav>
	<div>
		@RenderBody()
	</div>


	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - TasksEvaluation
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>


	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
	<script src="lib/wow/wow.min.js"></script>
	<script src="lib/easing/easing.min.js"></script>
	<script src="lib/waypoints/waypoints.min.js"></script>
	<script src="lib/owlcarousel/owl.carousel.min.js"></script>

	<!-- Template Javascript -->
	<script src="js/main.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>