TasksEvaluation.Web/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using TasksEvaluation.Core.Interfaces.IServices;
using TasksEvaluation.Core;
using TasksEvaluation.Core.DTOs;
using TaskEvaluation.InfraStructure.Repositories.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using TasksEvaluation.Core.Entities.Business;
using TasksEvaluation.Web.ViewModels;
using System.Data;
using Microsoft.AspNetCore.Authorization;
using System.Net.WebSockets;


namespace TasksEvaluation.Web.Controllers
{
	[Authorize]
	public class AssignmentController : Controller
	{

		private readonly IAssignmentService _assignmentService;
		private readonly IGroupService _groupService;
		private readonly IEvaluationGradeService _evaluationGradeService;
		private readonly IUnitOfWork _unitOfWork;
		public AssignmentController(IAssignmentService assignmentService, IUnitOfWork unitOfWork, IGroupService groupService, IEvaluationGradeService evaluationGradeService)
		{
			_assignmentService = assignmentService;
			_unitOfWork = unitOfWork;
			_groupService = groupService;
			_evaluationGradeService = evaluationGradeService;
		}
	
		public async Task<IActionResult> GetAllAssignments()
		{
			var assignments = await _assignmentService.GetAssignmentsIncludeGroups();
			 return View(assignments);

		
		}

        public ActionResult Create()
		{

			var selectedGroup = new GroupDto() { Id = 0, Title = "Select Group" };
			var allGroups = _groupService.GetAll().Result.ToList();
			allGroups.Add(selectedGroup);

			ViewBag.GroupId = new SelectList(allGroups, nameof(Group.Id), nameof(Group.Title)
				, allGroups.Find(c => c.Id == 0).Id);

			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
   
        public async Task<IActionResult> Create(AssignmentDto assignment)
		{
           
            if (ModelState.IsValid)
			{
				await _assignmentService.Create(assignment);
				await _unitOfWork.Complete();
				return RedirectToAction(nameof(GetAllAssignments));
			}

            var selectedGroup = new GroupDto() { Id = 0, Title = "Select Group" };
            var allGroups = _groupService.GetAll().Result.ToList();
            allGroups.Add(selectedGroup);
            ViewBag.GroupId = new SelectList(allGroups, nameof(Group.Id), nameof(Group.Title)
                , assignment.GroupId);
            return View(assignment);
		}

  
        public async Task<IActionResult> Edit(int? id)
		{

			if (id is null || !_assignmentService.Any().Result)
				return NotFound();
			var assignment = await _assignmentService.GetById(id.Value);
			var allGroups = _groupService.GetAll().Result.ToList();
			ViewBag.GroupId = new SelectList(allGroups, nameof(Group.Id), nameof(Group.Title)
				, assignment.GroupId);
			return View(assignment);

		}

		[HttpPost]
		[ValidateAntiForgeryToken]
    
        public async Task<IActionResult> Edit(AssignmentDto assignment)
		{
			if (assignment is null || !_assignmentService.Any().Result)
				return NotFound();
			if(ModelState.IsValid)
			{
				try
				{
					_assignmentService.Update(assignment);
					await _unitOfWork.Complete();
				}
				catch (DBConcurrencyException)
				{
					if (!_assignmentService.Contains(assignment).Result)
						return NotFound();
					throw;
				}
				return RedirectToAction(nameof(GetAllAssignments));
			}
			return View(assignment);
		}

   
        public async Task<IActionResult> Delete(int? id)
		{
			if (id is null || !_assignmentService.Any().Result)
				return NotFound();
			var assignment = await _assignmentService.GetById(id.Value);
			return View(assignment);
		}

		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
   
        public async Task<IActionResult> DeleteConfirmed(int id)
		{
			if (!_assignmentService.Any().Result)
				return NotFound();

			_assignmentService.Delete(id);
			await _unitOfWork.Complete();
			return RedirectToAction(nameof(GetAllAssignments));
		}

        [AllowAnonymous]
        public async Task<IActionResult> GetAssignmentsAccordingSpecificStudent(StudentDto student)
		{
			var assignments = await _assignmentService.GetAssignmentsAccordingSpecificStudent(student.GroupId);
			ViewData["Student"] = student;
			var grades = await _evaluationGradeService.GetAll();
			ViewData["Grades"] = grades;
			return View(assignments);
		}
	}
}

TasksEvaluation.Web/Controllers/EvaluationGradeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaskEvaluation.InfraStructure.Repositories.Services;
using TasksEvaluation.Core;
using TasksEvaluation.Core.DTOs;
using TasksEvaluation.Core.Interfaces.IServices;
using TasksEvaluation.Web.ViewModels;

namespace TasksEvaluation.Web.Controllers
{
    [Authorize]
    public class EvaluationGradeController : Controller
    {
        private readonly IEvaluationGradeService _evaluationGradeService;
		private readonly ISolutionService _solutionService;

		private readonly IUnitOfWork _unitOfWork;
        public EvaluationGradeController(IEvaluationGradeService evaluationGradeService , ISolutionService solutionService , IUnitOfWork unitOfWork)
        {
            _evaluationGradeService = evaluationGradeService;
			_solutionService = solutionService;
			_unitOfWork = unitOfWork;

        }
        public async Task<IActionResult> EvaluateSolution(int? solutionId )
        {
            var solution = await _solutionService.GetById(solutionId.Value);
            var grades =  _evaluationGradeService.GetAll().Result.ToList();
            var selectedGrade = new EvaluationGradeDto() { Id = 0, Grade = "Select Grade" };
            grades.Add(selectedGrade);
            ViewBag.GradeId = new SelectList(grades, nameof(EvaluationGradeDto.Id), nameof(EvaluationGradeDto.Grade),
                solution.GradeId ?? 0);
            
            ViewData["solution"] = solution;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task< IActionResult> EvaluateSolution(SolutionGradeVM solutionGradeVM)
        {
            var solution = await _solutionService.GetById(solutionGradeVM.SolutionId.Value);

            if (solutionGradeVM.GradeId != 0)
            {
                solution.GradeId = solutionGradeVM.GradeId;
                _solutionService.Update(solution);
                await _unitOfWork.Complete();
                return RedirectToAction(nameof(SolutionController.GetAllSolutions), "Solution");
            }
            ModelState.AddModelError(string.Empty, "Please Choose Grade");
			var grades = _evaluationGradeService.GetAll().Result.ToList();
			var selectedGrade = new EvaluationGradeDto() { Id = 0, Grade = "Select Grade" };
			grades.Add(selectedGrade);
			ViewBag.GradeId = new SelectList(grades, nameof(EvaluationGradeDto.Id), nameof(EvaluationGradeDto.Grade),
				solution.GradeId ?? 0);

			ViewData["solution"] = solution;
			return View(solutionGradeVM);
		}

        public async Task<IActionResult> ShowGrade(int solutionId)
        {
            var solution = await _solutionService.GetById(solutionId);
            if (solution is null)
                return NotFound();
 

            ViewBag.Grade = solution.GradeId is null ? "Please Waiting , Your Solution Under Evaluation."
                                                      : _evaluationGradeService.GetById(solution.GradeId.Value).Result.Grade;
            return View(solution) ;

		}
	}
}

TasksEvaluation.Web/Controllers/SolutionController.cs
using Microsoft.AspNetCore.Mvc;
using TaskEvaluation.InfraStructure.Repositories.Services;
using TasksEvaluation.Core;
using TasksEvaluation.Core.DTOs;
using TasksEvaluation.Core.Entities.Business;
using TasksEvaluation.Core.Interfaces.IServices;
using TasksEvaluation.Web.ViewModels;

namespace TasksEvaluation.Web.Controllers
{
	public class SolutionController : Controller
	{

		private readonly ISolutionService _solutionService;
		private readonly IStudentService _studentService;
		private readonly IUnitOfWork _unitOfWork;

		public SolutionController(ISolutionService solutionService, IUnitOfWork unitOfWork , IStudentService studentService)
		{
			_solutionService = solutionService;
			_unitOfWork = unitOfWork;
			_studentService = studentService;


		}

		public async Task<IActionResult> GetAllSolutions()
		{
			var solutions = await  _solutionService.GetAll();
			return View(solutions);
		}

		public IActionResult Create(int studentId , int assignmentId) // , string studentEmail
		{
			ViewData["StudentId"] = studentId;
			ViewData["AssignmentId"] = assignmentId;
			//var loginAsStudentVM = new LoginAsStudentVM();
			//loginAsStudentVM.Email = studentEmail;
			//ViewData["LoginAsStudentVM"] = loginAsStudentVM;
			return View();
		}


		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(SolutionCreateVM solutionVM)
		{
			if (ModelState.IsValid)
			{
				var solution = new SolutionDto()
				{
					AssignmentId = solutionVM.AssignmentId,
					StudentId = solutionVM.StudentId,
					Notes = solutionVM.Notes
				};
				if (solutionVM.SolutionFile != null)
				{
					string uploadsSolutionFilesFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads" ,"SolutionFiles");
					string fileName = Guid.NewGuid() + Path.GetExtension(solutionVM.SolutionFile.FileName);
					string filePath = Path.Combine(uploadsSolutionFilesFolder, fileName);


					using (var fileStream = new FileStream(filePath, FileMode.Create))
					{
						await solutionVM.SolutionFile.CopyToAsync(fileStream);
					}

					solution.SolutionFile = @$"/uploads/SolutionFiles/{fileName}";
				}
				await _solutionService.Create(solution);
				await _unitOfWork.Complete();
				var student = _studentService.GetById(solution.StudentId.Value).Result;
				return RedirectToAction(nameof(AssignmentController.GetAssignmentsAccordingSpecificStudent) ,"Assignment" , student);

			}
			return View(solutionVM);

		}

	}
}

TasksEvaluation.Web/Views/Assignment/Create.cshtml
@using TasksEvaluation.Core.DTOs 
@model AssignmentDto 

@{
	ViewData["Title"] = "Create";

}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
	option[value = "0"] {
		display: none;
	}
</style>

<h3>Create Assignment</h3>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Create" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@*  <div  class="form-group">
			<label asp-for="Id" class="control-label"></label>
			<input asp-for="Id" class="form-control" />
			<span asp-validation-for="Id" class="text-danger"></span>
			</div> *@
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Deadline" class="control-label"></label>
				<input asp-for="Deadline" class="form-control" />
				<span asp-validation-for="Deadline" class="text-danger"></span>
			</div>




			<div class="form-group">
				<label asp-for="GroupId" class="control-label">Group</label>
				<select asp-for="GroupId" class="form-control" asp-items="@ViewBag.GroupId">
				</select>
				<span asp-validation-for="GroupId" class="text-danger"></span>

			</div>
			<div class="form-group mt-3">
				<input type="submit" value="Create" class="btn btn-primary" />
				<a class="btn btn-secondary" asp-action="GetAllAssignments">Back to List</a>

			</div>

		</form>
	</div>
</div>

<div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TasksEvaluation.Web/Views/Assignment/Delete.cshtml
@using TasksEvaluation.Core.DTOs

@{
	ViewData["Title"] = "Delete";
}
@model AssignmentDto

@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}





<h3>Delete Assignment</h3>
<hr />

<div>
	<div>
		<strong>Title:</strong> @Model.Title
	</div>
	<div>
		<strong>Description:</strong> @Model.Description
	</div>
	<div>
		<strong>DeadLine:</strong> @Model.Deadline
	</div>
	<div>
		
	</div>
</div>


	<h3>Are you Sure to Delete @Model.Title ? </h3>
	<form asp-action="Delete">
		<div class="form-group">
			<input asp-for="Id" hidden class="form-control" />
			<input type="submit" value="Delete" class="btn btn-danger" />
			<a class="btn btn-secondary" asp-action="GetAllAssignments">Back To List</a>
		</div>


	</form>

TasksEvaluation.Web/Views/Assignment/Edit.cshtml
@using TasksEvaluation.Core.DTOs 
@model AssignmentDto 

@{
	ViewData["Title"] = "Edit";

}
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<style>
	option[value = "0"] {
		display: none;
	}
</style>

<h3>Edit Assignment</h3>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit" enctype="multipart/form-data">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			@*  <div  class="form-group">
			<label asp-for="Id" class="control-label"></label>
			<input asp-for="Id" class="form-control" />
			<span asp-validation-for="Id" class="text-danger"></span>
			</div> *@
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description" class="control-label"></label>
				<input asp-for="Description" class="form-control" />
				<span asp-validation-for="Description" class="text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Deadline" class="control-label"></label>
				<input asp-for="Deadline" class="form-control" />
				<span asp-validation-for="Deadline" class="text-danger"></span>
			</div>




			<div class="form-group">
				<label asp-for="GroupId" class="control-label">Group</label>
				<select asp-for="GroupId" class="form-control" asp-items="@ViewBag.GroupId">
				</select>
			</div>
			<div class="form-group mt-3">
				<input type="submit" value="Save" class="btn btn-primary" />
				<a class="btn btn-secondary" asp-action="GetAllAssignments">Back to List</a>

			</div>

		</form>
	</div>
</div>

<div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TasksEvaluation.Web/Views/Assignment/GetAllAssignments.cshtml
@using TasksEvaluation.Core.DTOs
@using Microsoft.AspNetCore.Identity
@using TasksEvaluation.Web.Controllers
@inject SignInManager<IdentityUser> signInManager
@model IEnumerable<AssignmentDto>
@{
	ViewData["Title"] = "All Assignments";
	var student = ViewData["Student"] as StudentDto;
}
@{
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

	<h4 class="">Assignment List</h4>
	<a asp-controller="Assignment" asp-action="Create" class="btn btn-added float-end btn-info mb-3"><img src="/images/plus.svg" alt="img">Add New Assignment</a>
	<p>Manage Your Assignments</p>

	<div class="text-center">

		<table class="table table-bordered table-striped">
			<tr>
				<th>Assignment Title</th>
				<th>Assignment Description</th>
				<th>Assignment DeadLine</th>
				<th>Group</th>
				<th></th>
			</tr>
			@foreach (var assignment in Model)
			{
				<tr>
					<td class="">@assignment.Title</td>
					<td>@assignment.Description</td>
					<td>@assignment.Deadline</td>
					<td>@assignment.Group.Title</td>
					<td>
						<a class="btn btn-primary" asp-action="Edit" asp-route-id="@assignment.Id">Edit</a>
						<a class="btn btn-danger" asp-action="Delete" asp-route-id="@assignment.Id">Delete</a>
					</td>
				</tr>
			}
		</table>
	</div>

TasksEvaluation.Web/Views/Assignment/GetAssignmentsAccordingSpecificStudent.cshtml
@using TasksEvaluation.Core.DTOs
@using TasksEvaluation.Web.Controllers
@model IEnumerable<AssignmentDto>
@{
	ViewData["Title"] = "Assignments Per Student";
	var student = ViewData["Student"] as StudentDto;
	var grades = ViewData["Grades"] as IEnumerable<EvaluationGradeDto>;
}


<h3 class="text-center mt-4">Your Assignment List</h3>

<div class="container d-flex m-2">
	<div class="row container-fluid">
	@foreach (var assignment in Model)
	{
		  
@* 				int x = assignment.Solutions.Where(s => s.StudentId == student.Id).Count();
			
		<h1>@x</h1>
		<h1>@student.Id</h1> *@
		<div class="col-sm-4">
			<div class="card">
				<div class="card-body text-center">
					<h5 class="card-title">@assignment.Title</h5>
					<h5 class="card-title">@assignment.Description</h5>
					<p class="card-text text-danger fw-bold">DeadLine : @assignment.Deadline</p>
					@if (assignment.Solutions.Where(s => s.StudentId == student.Id).Count() == 0 @* || assignment.Solutions.Any(s => s.StudentId != student.Id)  *@ ) 
					{
						<a class="btn btn-primary" href="@Url.Action(nameof(SolutionController.Create),"Solution",
										new { studentId = student.Id, assignmentId = assignment.Id  })">Upload Solution</a>

					}
					else
					{
						<button class="btn btn-success" type="submit" disabled="disabled">Solution Uploaded</button>
						@*  <a class="btn btn-secondary" href="@Url.Action(nameof(EvaluationGradeController.ShowGrade),"EvaluationGrade",
										new { solutionId = assignment.Solution.Id})">Show Grade</a>  *@
						<h5 class="mt-2">
							@{
								if(assignment.Solutions.Where(s => s.StudentId == student.Id)?.FirstOrDefault().GradeId is null)
								{
									@:Your Solution Under Evaluation.
								} else
								{
									@:Grade : @grades.FirstOrDefault(e => e.Id == assignment.Solutions.FirstOrDefault(s => s.StudentId == student.Id).GradeId).Grade
								}

							}
						</h5>
					}
				</div>
			</div>
	</div>
		

	}

	</div>
</div>